import Cocoa
//code generated by postman for deleting a book with the id = 4aeb70e9.....
var request = URLRequest(url: URL(string: "https://library-api.postmanlabs.com/books/4aeb70e9-abbb-42a0-a692-d473900a3baa")!,timeoutInterval: Double.infinity)
request.addValue("postmanrulz", forHTTPHeaderField: "api-key")

request.httpMethod = "DELETE"

let task = URLSession.shared.dataTask(with: request) { data, response, error in
  guard let data = data else {
    print(String(describing: error))
    return
  }
  print(String(data: data, encoding: .utf8)!)
}

task.resume()
